# Generated by Django 3.2.2 on 2021-05-10 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ColourVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Colour Variations',
            },
        ),
        migrations.CreateModel(
            name='SizeVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Size Variations',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'SubCategories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='product_images')),
                ('description', models.TextField()),
                ('price', models.IntegerField(default=0, help_text='in US dollars $')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('has_colours', models.BooleanField(default=False)),
                ('has_sizes', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('available_colours', models.ManyToManyField(default=None, to='productApp.ColourVariation')),
                ('available_sizes', models.ManyToManyField(default=None, to='productApp.SizeVariation')),
                ('primary_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_products_category', to='productApp.category')),
                ('secondary_categories', models.ManyToManyField(blank=True, related_name='sub_products_category', to='productApp.SubCategory')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='IngredientsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients_category', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('average_price_per_kilo', models.FloatField(blank=True, default='1.0', null=True)),
                ('received_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('received_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issued_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issued_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issued_to', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('date_last_updated', models.DateTimeField(null=True)),
                ('date_created', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='productApp.category')),
            ],
            options={
                'verbose_name_plural': 'Ingredients History',
            },
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_category', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.IntegerField(default='0', null=True)),
                ('average_price_per_kilo', models.FloatField(blank=True, default='', null=True)),
                ('received_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('received_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issued_quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('issued_by', models.CharField(blank=True, max_length=50, null=True)),
                ('issued_to', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('date_last_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='productApp.category')),
            ],
            options={
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula_category', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity_of_ingredients', models.IntegerField(default='0', null=True)),
                ('ingredient_1_percentage', models.FloatField(blank=True, null=True)),
                ('ingredient_2_percentage', models.FloatField(blank=True, null=True)),
                ('ingredient_3_percentage', models.FloatField(blank=True, null=True)),
                ('ingredient_4_percentage', models.FloatField(blank=True, null=True)),
                ('ingredient_5_percentage', models.FloatField(blank=True, null=True)),
                ('ingredient_6_percentage', models.FloatField(blank=True, null=True)),
                ('ingredient_7_percentage', models.FloatField(blank=True, null=True)),
                ('ingredient_8_percentage', models.FloatField(blank=True, null=True)),
                ('ingredient_9_percentage', models.FloatField(blank=True, null=True)),
                ('ingredient_10_percentage', models.FloatField(blank=True, null=True)),
                ('average_price_per_kilo', models.FloatField(blank=True, null=True)),
                ('average_cost_key_code', models.CharField(blank=True, max_length=10, null=True)),
                ('sum', models.IntegerField(default='1000', null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default='0', null=True)),
                ('date_last_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='productApp.category')),
                ('ingredient_1', models.ForeignKey(blank=True, default='Blank', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_1', to='productApp.ingredients')),
                ('ingredient_10', models.ForeignKey(blank=True, default='Blank', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_10', to='productApp.ingredients')),
                ('ingredient_2', models.ForeignKey(blank=True, default='Blank', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_2', to='productApp.ingredients')),
                ('ingredient_3', models.ForeignKey(blank=True, default='Blank', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_3', to='productApp.ingredients')),
                ('ingredient_4', models.ForeignKey(blank=True, default='Blank', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_4', to='productApp.ingredients')),
                ('ingredient_5', models.ForeignKey(blank=True, default='Blank', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_5', to='productApp.ingredients')),
                ('ingredient_6', models.ForeignKey(blank=True, default='Blank', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_6', to='productApp.ingredients')),
                ('ingredient_7', models.ForeignKey(blank=True, default='Blank', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_7', to='productApp.ingredients')),
                ('ingredient_8', models.ForeignKey(blank=True, default='Blank', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_8', to='productApp.ingredients')),
                ('ingredient_9', models.ForeignKey(blank=True, default='Blank', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_9', to='productApp.ingredients')),
            ],
            options={
                'verbose_name_plural': 'Formulas',
            },
        ),
    ]
