# Generated by Django 3.2.2 on 2021-05-10 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_colours',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
        migrations.DeleteModel(
            name='ColourVariation',
        ),
        migrations.DeleteModel(
            name='SizeVariation',
        ),
    ]
